language: node_js
sudo: required
node_js:
  - "node"
addons:
  chrome: stable
script:
  - npx ng build core
  - npm install ./dist/core/
  - npx ng build ng-connector
  - npm install ./dist/ng-connector/
  - npx ng build ng-ui-material
  - npm install ./dist/ng-ui-material/
  - npx ng build demo
